### ISSUE TITLE
Download all files button only downloads one artifact

### ISSUE THREAD

**Issue by felipecrs** [jenkinsci/artifactory-artifact-manager-plugin#99]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
```text
Jenkins: 2.492.1
OS: Linux - 6.8.0-52-generic
Java: 21.0.6 - Eclipse Adoptium (OpenJDK 64-Bit Server VM)
---
Parameterized-Remote-Trigger:3.2.1
allure-jenkins-plugin:2.32.0
ansicolor:1.0.6
antisamy-markup-formatter:162.v0e6ec0fcfcf6
apache-httpcomponents-client-4-api:4.5.14-269.vfa_2321039a_83
artifactory-artifact-manager:190.vfca_09a_223ca_2
artifactory-client-api:2.19.0-82.va_7314a_427046
asm-api:9.7.1-97.v4cc844130d97
audit-trail:382.vf64d6f626060
authentication-tokens:1.119.v50285141b_7e1
authorize-project:2.0.0
basic-branch-build-strategies:190.v343a_ee70d920
blueocean:1.27.16
blueocean-bitbucket-pipeline:1.27.16
blueocean-commons:1.27.16
blueocean-config:1.27.16
blueocean-core-js:1.27.16
blueocean-dashboard:1.27.16
blueocean-display-url:2.4.3
blueocean-events:1.27.16
blueocean-git-pipeline:1.27.16
blueocean-github-pipeline:1.27.16
blueocean-i18n:1.27.16
blueocean-jwt:1.27.16
blueocean-personalization:1.27.16
blueocean-pipeline-api-impl:1.27.16
blueocean-pipeline-editor:1.27.16
blueocean-pipeline-scm-api:1.27.16
blueocean-rest:1.27.16
blueocean-rest-impl:1.27.16
blueocean-web:1.27.16
bootstrap5-api:5.3.3-2
bouncycastle-api:2.30.1.80-256.vf98926042a_9b_
branch-api:2.1214.v3f652804588d
build-name-setter:2.5.0
build-timeout:1.36
caffeine-api:3.2.0-161.v691ef352cee1
checks-api:2.2.3
cloudbees-bitbucket-branch-source:935.0.0
cloudbees-disk-usage-simple:232.v713eeed2e1f4
cloudbees-folder:6.982.vf165a_16c9507
cloudbees-jenkins-advisor:358.v58972d19b_1f0
command-launcher:118.v72741845c17a_
commons-compress-api:1.27.1-2
commons-lang3-api:3.17.0-84.vb_b_938040b_078
commons-text-api:1.13.0-153.v91dcd89e2a_22
configuration-as-code:1932.v75cb_b_f1b_698d
copyartifact:765.v0357cc6e6eb_3
coverage:2.1.0
credentials:1408.va_622a_b_f5b_1b_1
credentials-binding:687.v619cb_15e923f
cucumber-reports:5.8.5
dark-theme:524.vd675b_22b_30cb_
data-tables-api:2.2.2-1
display-url-api:2.209.v582ed814ff2f
docker-commons:445.v6b_646c962a_94
docker-workflow:596.v3e6972b_46b_e2
durable-task:581.v299a_5609d767
echarts-api:5.5.1-6
eddsa-api:0.3.0-4.v84c6f0f4969e
email-ext:1876.v28d8d38315b_d
embeddable-build-status:548.v5653c6e28c41
extended-read-permission:61.vf24570ff3b_e9
favorite:2.225.v68765b_b_a_1fa_3
file-parameters:358.v9ed4456a_169a_
flatpickr-api:4.6.13-15.vf6e534338831
font-awesome-api:6.7.2-1
forensics-api:3.0.0
gerrit-code-review:0.4.9
gerrit-trigger:2.42.0
git:5.7.0
git-client:6.1.2
github:1.41.0
github-api:1.321-478.vc9ce627ce001
github-branch-source:1810.v913311241fa_9
gitlab-api:5.6.0-97.v6603a_83f8690
gitlab-branch-source:718.v40b_5f0e67cd3
gson-api:2.12.1-113.v347686d6729f
handy-uri-templates-2-api:2.1.8-30.v7e777411b_148
htmlpublisher:1.37
instance-identity:201.vd2a_b_5a_468a_a_6
ionicons-api:74.v93d5eb_813d5f
jackson2-api:2.17.0-389.va_5c7e45cd806
jacoco:3.3.7
jakarta-activation-api:2.1.3-1
jakarta-mail-api:2.1.3-1
javadoc:310.v032f3f16b_0f8
javax-activation-api:1.2.0-7
javax-mail-api:1.6.2-10
jaxb:2.3.9-1
jdk-tool:83.v417146707a_3d
jenkins-design-language:1.27.16
jersey2-api:2.45-154.v4ded3dc34f81
jjwt-api:0.11.5-112.ve82dfb_224b_a_d
job-dsl:1.90
joda-time-api:2.13.1-115.va_6b_5f8efb_1d8
jquery3-api:3.7.1-3
jsch:0.2.16-86.v42e010d9484b_
json-api:20250107-125.v28b_a_ffa_eb_f01
json-path-api:2.9.0-148.v22a_7ffe323ce
junit:1316.v13ec14a_de230
kubernetes:4313.va_9b_4fe2a_0e34
kubernetes-client-api:6.10.0-240.v57880ce8b_0b_2
kubernetes-credentials:190.v03c305394deb_
ldap:776.vddf3e325103b_
lockable-resources:1349.v8b_ccb_c5487f7
mailer:489.vd4b_25144138f
matrix-auth:3.2.4
matrix-project:845.vffd7fa_f27555
metrics:4.2.21-461.v881e35d8fa_b_a_
mina-sshd-api-common:2.14.0-143.v2b_362fc39576
mina-sshd-api-core:2.14.0-143.v2b_362fc39576
next-executions:402.va_4407095f22a_
okhttp-api:4.11.0-183.va_87fc7a_89810
pipeline-build-step:555.v589d5c24a_3d6
pipeline-graph-analysis:231.v56354571a_da_0
pipeline-graph-view:409.v98f212e980b_4
pipeline-groovy-lib:752.vdddedf804e72
pipeline-input-step:513.v7eb_fe7e2c0fc
pipeline-milestone-step:119.vdfdc43fc3b_9a_
pipeline-model-api:2.2221.vc657003fb_d93
pipeline-model-definition:2.2221.vc657003fb_d93
pipeline-model-extensions:2.2221.vc657003fb_d93
pipeline-rest-api:2.37
pipeline-stage-step:312.v8cd10304c27a_
pipeline-stage-tags-metadata:2.2221.vc657003fb_d93
pipeline-stage-view:2.37
pipeline-utility-steps:2.19.0
plain-credentials:183.va_de8f1dd5a_2b_
plugin-usage-plugin:4.9
plugin-util-api:6.0.0
prism-api:1.29.0-19
prometheus:819.v50953a_c560dd
pubsub-light:1.18
purge-build-queue-plugin:88.v23b_97b_f2c7a_d
rebuild:338.va_0a_b_50e29397
resource-disposer:0.25
role-strategy:756.v978cb_392eb_d3
saferestart:102.v4dc1b_9636a_ee
schedule-build:643.v58b_09e4b_748c
scm-api:703.v72ff4b_259600
script-security:1373.vb_b_4a_a_c26fa_00
snakeyaml-api:2.3-123.v13484c65210a_
sonar:2.18
sonar-gerrit:388.v9b_f1cb_e42306
sse-gateway:1.27
ssh-credentials:349.vb_8b_6b_9709f5b_
sshd:3.353.v2b_d33c46e970
structs:338.v848422169819
support-core:1575.v49b_01a_460e3b_
theme-manager:278.v2e3c063e42cc
timestamper:1.28
token-macro:444.v52de7e9c573d
trilead-api:2.147.vb_73cc728a_32e
uno-choice:2.8.6
variant:70.va_d9f17f859e0
workflow-aggregator:600.vb_57cdd26fdd7
workflow-api:1363.v03f731255494
workflow-basic-steps:1079.vce64b_a_929c5a_
workflow-cps:4018.vf02e01888da_f
workflow-durable-task-step:1405.v1fcd4a_d00096
workflow-job:1505.vea_4b_20a_4a_495
workflow-multibranch:800.v5f0a_a_660950e
workflow-scm-step:427.v4ca_6512e7df1
workflow-step-api:686.v603d058a_e148
workflow-support:946.v2a_79d8a_4b_e14
ws-cleanup:0.48
```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Ubuntu 24.04 for both agents and controller

### Reproduction steps

1. Run a pipeline that archives several files
2. Try to download them all using the _(all files in zip)_ button from the build `/artifact` page

### Expected Results

To have all files in the downloaded zip, as the button implies.

### Actual Results

There's only one file in the downloaded zip.

### Are you interested in contributing a fix?

Not right now, sorry. :(

**Comment by felipecrs** [comment]
I believe the plugin could simply forward the button request to Artifactory:

```
https://myartifactory.com/ui/api/v1/ui/artifactactions/downloadfolder?repoKey=jenkins-generic-local&path=artifacts%2Fmyproject%2Fmaster%2Fbuildproject%2F4672%2Fartifacts&archiveType=zip&includeChecksumFiles=false
```

Which will download all artifacts for that build in a zip file.

**Comment by Nitrael86** [comment]
We have the same problem, is there already any progress?

**Comment by jonesbusy** [comment]
Feel free to open a PR. It's open source. I'm more than happy to review any PR if this issue is important for you or your company

The plugin only implement ArtifactManager: https://github.com/jenkinsci/artifactory-artifact-manager-plugin/blob/main/src/main/java/io/jenkins/plugins/artifactory_artifacts/ArtifactoryArtifactManager.java#L35

I don't know how the `all files in zip` button is suppose to work. Even if it's something that can be overriden/fixed at plugin level.

For the moment I don't see any difference with other artifact manager implementation (Like S3: https://github.com/jenkinsci/artifact-manager-s3-plugin/blob/master/src/main/java/io/jenkins/plugins/artifact_manager_jclouds/JCloudsArtifactManager.java)

**Comment by jonesbusy** [comment]
Fixed on https://github.com/jenkinsci/artifactory-artifact-manager-plugin/releases/tag/252.v944a_69ea_4873

**Comment by Nitrael86** [comment]
Can you please reopen this issue, its still not working

**Comment by byian** [comment]
I've tested it in the production environment and can confirm the problem still exists.
I'm still trying to reproduce it in the testing environment but haven't had any success so far. I’ll give it a few more attempts.

Not sure if it helps, but we could try implement [zip](https://javadoc.jenkins.io/jenkins/util/VirtualFile.html#zip(java.io.OutputStream,java.lang.String,java.lang.String,boolean,java.lang.String,java.nio.file.OpenOption...))

@jonesbusy reopen pls

**Comment by jonesbusy** [comment]
Sure, but it would be great to have a reproducer: https://github.com/jenkinsci/artifactory-artifact-manager-plugin/pull/124#issuecomment-3134928652

And information about your environment (https://www.jenkins.io/participate/report-issue/)
